spring:
  application:
    name: product_rest_api
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:product_db
    username: zuzz
    password: zuzz
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect